global: 
  applicationName: wcag
image:
  name: gcr.io/g5-images/accessibility-report
configurations:
  staging:
    configMapData:
      BROWSER_URL: 'https://accessibility-opex-staging.g5devops.com'
      BASE_URL: 'accessibility-opex-staging.g5devops.com'
  prime:
    configMapData:
      BROWSER_URL: 'https://accessibility-opex-prime.g5devops.com'
      BASE_URL: 'accessibility-opex-prime.g5devops.com'
  production:
    configMapData:
      BROWSER_URL: 'https://accessibility.g5marketingcloud.com/'
      BASE_URL: 'accessibility.g5marketingcloud.com'
