apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{ include "accessibility.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    {{ include "accessibility.selectorLabels" . | nindent 4 }}
