<template>
  <div
    :class="[{ 'is-hidden': !isVisible }, drawerStyles, 'drawer-container', 'bg-white']"
  >
    <transition
      type="animation"
      name="shake-vertical"
      appear
      appear-to-class="shake-vertical"
    >
    <b-btn
      id="toggle-drawer"
      :class="btnStyles"
      :disabled="options.isDisabled"
      @click="isVisible = !isVisible"
      variant="primary"
      class="drawer-btn p-0"
    >
      <slot name="button-text">
        <left-caret v-if="isVisible" :color="`currentColor`" />
        <right-caret v-else :color="`currentColor`" />
      </slot>
    </b-btn>
    </transition>
    <b-card no-body class="drawer-content border-0">
      <slot name="content" />
    </b-card>
  </div>
</template>

<script>
import LeftCaret from '~/components/icons/left-caret'
import RightCaret from '~/components/icons/right-caret'
export default {
  components: {
    LeftCaret,
    RightCaret
  },
  props: {
    options: {
      type: Object,
      default() {
        return {
          position: 'left',
          slot: 'center',
          fullHeight: true,
          tab: true,
          isDisabled: false
        }
      }
    }
  },
  data() {
    return {
      isVisible: false
    }
  },
  computed: {
    drawerStyles() {
      return (this.options.position === 'left')
        ? (this.options.fullHeight)
          ? 'full-height attach-left'
          : 'attach-left'
        : (this.options.fullHeight)
          ? 'full-height attach-right'
          : 'attach-right'
    },
    btnStyles() {
      return (this.options.tab)
        ? 'tab-btn'
        : 'round-btn'
    }
  }
}
</script>

<style lang="scss" scoped>
.drawer-container {
  position: fixed;
  padding-bottom: 10px;
  top: 50%;
  min-width: 300px;
  z-index: 23;
  transition: 200ms ease-out;
  transition-delay: 100ms;
  transform: translate(0%, 0%);
  &.full-height {
    top: 0;
    bottom: 0;
  }
}
@media (min-width: 768px) {
  .drawer-container {
    width: 300px;
  }
}
@media (min-width: 992px) {
  .drawer-container {
    width: calc((100vw - 960px) / 2);
  }
}
@media (min-width: 1200px) {
  .drawer-container {
    width: calc((100vw - 1140px) / 2);
  }
}
.drawer-container:not(.is-hidden),
.drawer-container:hover {
  box-shadow: 15px 0 30px rgba(0, 0, 0, 0.2);
}
.drawer-container:not(.full-height) {
  box-shadow: 0 0 50px rgba(0, 0, 0, 0.2);
  transform: translate(0%, -50%);
}
.drawer-btn {
  position: absolute;
  top: 50%;
  z-index: 23;
}
.attach-right {
  right: 0;
}
.attach-left {
  left: 0;
}
.attach-right.is-hidden {
  transform: translate(100%, 0%);
}
.attach-left.is-hidden {
  transform: translate(-100%, 0%);
}
.attach-right:not(.full-height).is-hidden {
  transform: translate(100%, -50%);
}
.attach-left:not(.full-height).is-hidden {
  transform: translate(-100%, -50%);
}
.attach-right > .drawer-btn {
  left: 0;
  border-radius: 10px 0 0 10px;
  transform: translate(-100%, -50%);
}
.attach-left > .drawer-btn {
  right: 0;
  border-radius: 0 10px 10px 0;
  transform: translate(100%, -50%);
}
.full-height .drawer-btn {
  top: 10%;
}
.full-height::before {
  position: absolute;
  z-index: 21;
  top: 0%;
  height: 100%;
  right: 0;
  width: 60px;
  content: "";
  transform: translate(100%, 0%);
}
.full-height.is-hidden:hover {
  transform: translate(-95%, 0%);
}
.drawer-content {
  overflow-x: hidden;
  overflow-y: scroll;
  height: 100%;
}
.tab-btn {
  height: 60px;
  width: 30px;
}
.round-btn {
  width: 30px;
  min-height: 30px;
}
.drawer-btn:focus,
.drawer-btn:active {
  outline: none;
}
.shake-vertical {
  animation: shake-vertical 900ms 1500ms cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-2-28 8:4:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation shake-vertical
 * ----------------------------------------
 */
@keyframes shake-vertical {
  0%,
  100% {
    transform: translate(100%, -50%);
  }
  10%,
  30%,
  50%,
  70% {
    transform: translate(100%, calc(-50% - 8px));
  }
  20%,
  40%,
  60% {
    transform: translate(100%, calc(-50% + 8px));
  }
  80% {
    transform: translate(100%, calc(-50% + 6.4px));
  }
  90% {
    transform: translate(100%, calc(-50% - 6.4px));
  }
}

@media print {
  .drawer-container,
  .drawer-btn {
    display: none;
  }
}
</style>
